### ISSUE TITLE
Missing/wrong qt modules in pyqt6

### ISSUE THREAD

**Issue by GiganticThirstyHerald** [justengel/resource_man#1]
I was trying to compile qrc file and got some errors:
First of all, I had to manually install ```dynamicmethod``` and ```qtpy``` after installing resource_man - ```qt.py``` gave me an import error on lines 7 and 8
Also, there's an error in import from qtpy module ```AttributeError: module 'qtpy.QtSvg' has no attribute 'QSvgWidget'``` - this refers to a ```class QSvgWidget(QtSvg.QSvgWidget):``` on 385 line
QSvgWidget in pyqt6 is a child of QtSvgWidgets I assume, it's trying to reach out wrong module. I've tried manually import QtSvgWidgets from qtpy, but it can't find it

Win10 x64, PyQt6

**Comment by justengel** [comment]
Qt is a mess. Unfortunately the `qtpy` library is not up to date with Qt 6. I made an update to the library and this should be fixed in version `resource_man==2.2.8`. 

As for installation. This library can be used without Qt. There is a requirements_qt.txt file to document the dependencies for Qt. The setup.py file also has an extra_requires section, so you can install the library with qt dependencies using `pip install resource_man[qt]`.
